### ISSUE TITLE
Error: Cannot find module 'y-protocols/dist/awareness.cjs'

### ISSUE THREAD

**Issue by devgeni** [yjs/y-prosemirror#59]
**Describe the bug**
I'm desperate. I can't understand the nature of this bug. This happens in AWS Elastic Beanstalk Linux environment. In my local nodejs v14 environment on my MacOS machine it all works without errors. I'm developing a collaboration application based on `@hocuspocus` backend solution. This backend uses the `@hocuspocus/transformer` package that requires `y-prosemirror`. 
I compile source files to js with typescript using "CommonJS" module option. When I deploy compiled code to Beanstalk I get this error:
```
Error: Cannot find module 'y-protocols/dist/awareness.cjs'
Require stack:
- /var/app/current/node_modules/y-prosemirror/dist/y-prosemirror.cjs
- /var/app/current/node_modules/@hocuspocus/transformer/dist/hocuspocus-transformer.cjs
- /var/app/current/lib/index.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
at Function.Module._load (internal/modules/cjs/loader.js:667:27)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/var/app/current/node_modules/y-prosemirror/dist/y-prosemirror.cjs:8:1)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/var/app/current/node_modules/y-prosemirror/dist/y-prosemirror.cjs',
'/var/app/current/node_modules/@hocuspocus/transformer/dist/hocuspocus-transformer.cjs',
'/var/app/current/lib/index.js'
]
}
```

**To Reproduce**
Well, I'll try to describe the process...
1. Create AWS Elastic Beanstalk application.
2. Write some ts code that uses `@hocuspocus/transformer` `TiptapTransformer.toYdoc` function and compile it to js.
Here is a part of tsconfig.json:
```
{
...
  "compilerOptions": {
      "esModuleInterop": true,
      "module": "CommonJS",
      "noImplicitAny": false,
      "noImplicitReturns": true,
      "noUnusedLocals": true,
      "outDir": "lib",
      "sourceMap": false,
      "strict": false,
      "target": "ES2017",
      "skipLibCheck": true
    }
...
}
```
3. Upload this code as a zip file to Beanstalk.
4. See Health "Severe" status and open logs to look at the error.

**Expected behavior**
I wanted my application to work on AWS Elastic Beanstalk as it did locally.

**Environment Information**
 - nodejs v14
 - y-prosemirror@1.0.9
 - y-protocols@1.0.5

**Additional context**
Could this be related? [https://github.com/yjs/y-protocols/issues/3](https://github.com/yjs/y-protocols/issues/3)

**Comment by devgeni** [comment]
I resolved it by explicitly adding `y-prosemirror` and `y-protocols` to `package.json`.
